version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5433:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5433/dbname
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis